Validador/Validadores2/config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :products
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Validador/Validadores2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Validador/Validadores2/app/models/category.rb
class Category < ApplicationRecord
	has_many :category_product
	has_many :products, through: :category_product
end

Validador/Validadores2/app/models/category_product.rb
class CategoryProduct < ApplicationRecord
  belongs_to :category
  belongs_to :product
end

Validador/Validadores2/app/models/product.rb
class Product < ApplicationRecord

	has_many :category_product
	has_many :categories, through: :category_product 

	validates :marca, :referencia, :costo, presence:true
	#validates :talla, exclusion: {in: %w(s m), message:"%{value} no manejamos esta talla"}
	#validates :color, inclusion: { in: %w(Rojo Verde Azul Amarillo Blanco),
    			#message: "%{value} Este color no esta disponible" }
	validates :description, length: { maximum: 140}
	validates :costo, numericality: { only_integer:true, greater_than: 0}
	before_save :calcular_total

	def calcular_total
		self.total= self.costo + self.costo * 0.16
	end

end

Validador/Validadores2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Validador/Validadores2/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :color)
    end
end

Validador/Validadores2/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
   @products = Product.all
   #@productos = Product.find(10)
   #@productos = Product.take(10)
   #@productos = Product.first
   #@productos = Product.last
   #@productos = Product.find_by_color("blanco")
   #@productos = Product.where(talla: ["s", "l"])
   #@productos = Product.where.not(talla: ["s", "l"])
   #@productos = Product.order(:marca)
   #@productos = Product.select(:costo, :total)
   #@productos = Product.limit(3).offset(10)
   #@productos = Product.group(:talla)
   #@productos = Product.group(:marca).having("sum(costo) < ?", 2000)
   #@productos = Product.all.readonly
   #@productos = Product.where("color > ? AND marca = ?", "rojo", "polo")
   #@productos = Product.where("descripcion like  ? ",  "%#{params[:consulta]}%")
   #pluck, sum, minimum, maximum, average#@productos = Product.all
   #@productos = Product.find(10)
   #@productos = Product.take(10)
   #@productos = Product.first
   #@productos = Product.last
   #@productos = Product.find_by_color("blanco")
   #@productos = Product.where(talla: ["s", "l"])
   #@productos = Product.where.not(talla: ["s", "l"])
   #@productos = Product.order(:id, :marca)
   #@productos = Product.select(:costo, :total)
   #@productos = Product.limit(3).offset(10)
   #@productos = Product.group(:talla)
   #@productos = Product.group(:marca).having("sum(costo) < ?", 2000)
   #@productos = Product.all.readonly
   #@productos = Product.where("color > ? AND marca = ?", "rojo", "polo")
   #@productos = Product.where("descripcion like  ? ",  "%#{params[:consulta]}%")
   #pluck, sum, minimum, maximum, average
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:marca, :talla, :referencia, 
        :color, :costo, :total, :description, {category_id: []})
    end
end

Validador/Validadores2/app/helpers/application_helper.rb
module ApplicationHelper
end

Validador/Validadores2/app/helpers/categories_helper.rb
module CategoriesHelper
end

Validador/Validadores2/app/helpers/products_helper.rb
module ProductsHelper
end

Validador/Validadores2/app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
b
  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Validador/Validadores2/app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

Validador/Validadores2/app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.color %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

Validador/Validadores2/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

Validador/Validadores2/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @category.color %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

Validador/Validadores2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Validadores2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Validador/Validadores2/app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marca %>
    <%= f.text_field :marca, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :talla %>
    <%= f.text_field :talla, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :referencia %>
    <%= f.text_field :referencia, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="field">
    <%= f.label :costo %>
    <%= f.text_field :costo %>
  </div>

  <div class="field">
    <%= f.label :total %>
    <%= f.text_field :total %>
  </div>

 <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit class:"OK" %>
  </div>
<% end %>

Validador/Validadores2/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

Validador/Validadores2/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Marca</th>
      <th>Talla</th>
      <th>Referencia</th>
      <th>Color</th>
      <th>Costo</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %> -->
      <tr>
      <td><%= product.id %></td>
        <td><%= product.marca %></td>
        <td><%= product.talla %></td>
        <td><%= product.referencia %></td>
        <td><%= product.color %></td>
        <td><%= product.costo %></td>
        <td><%= product.total %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <!--<% end %> -->
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

Validador/Validadores2/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

Validador/Validadores2/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marca:</strong>
  <%= @product.marca %>
</p>

<p>
  <strong>Talla:</strong>
  <%= @product.talla %>
</p>

<p>
  <strong>Referencia:</strong>
  <%= @product.referencia %>
</p>

<p>
  <strong>Color:</strong>
  <%= @product.color %>
</p>

<p>
  <strong>Costo:</strong>
  <%= @product.costo %>
</p>

<p>
  <strong>Total:</strong>
  <%= @product.total %>
</p>

<ul>
  <%= @product.categories.each do |category| %>
  <li><%= category.name %></li>
  <%end%>
</ul>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>